-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE DATABASE `sms` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;

REATE TABLE sms.student (
	id BIGINT NOT NULL,
	email VARCHAR(255) NULL,
	first_name VARCHAR(255) NULL,
	last_name VARCHAR(255) NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;
